# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be5a2d3fb3d70b7909c27cbfd40559219ddb127c1e3d0156c729a46be1b02d7c89ec0472d4a686a6f30badf40ab0964c37ef7ca041a1b8d3736b954ce881d1af

test:
  secret_key_base: 9d34fe107eb95554659238d317a21f5419842bfc4a67926dabbe92797bc2226ca617d0b20ea10d216b6b787dccb5686a4368ce901fae72cb343d4c8123162f27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
